#if ENABLE_IL2CPP

// This file was generated by FMOD for Unity from the Static Plugins list in the FMOD settings.

using System;
using System.Runtime.InteropServices;

namespace FMODUnity
{
    class StaticPluginManager
    {
        [DllImport("__Internal")]
        private static extern IntPtr FMOD_ResonanceAudioSource_GetDSPDescription();

        [DllImport("__Internal")]
        private static extern IntPtr FMOD_ResonanceAudioSoundfield_GetDSPDescription();

        [DllImport("__Internal")]
        private static extern IntPtr FMOD_ResonanceAudioListener_GetDSPDescription();

        [DllImport(FMOD.VERSION.dll)]
        private static extern FMOD.RESULT FMOD5_System_RegisterDSP(IntPtr system, IntPtr description, IntPtr handle);

        public static void Register(FMOD.System coreSystem, Action<FMOD.RESULT, string> reportResult)
        {
            FMOD.RESULT result;

            result = FMOD5_System_RegisterDSP(coreSystem.handle, FMOD_ResonanceAudioSource_GetDSPDescription(), IntPtr.Zero);
            reportResult(result, "Registering static plugin 'FMOD_ResonanceAudioSource_GetDSPDescription'");

            result = FMOD5_System_RegisterDSP(coreSystem.handle, FMOD_ResonanceAudioSoundfield_GetDSPDescription(), IntPtr.Zero);
            reportResult(result, "Registering static plugin 'FMOD_ResonanceAudioSoundfield_GetDSPDescription'");

            result = FMOD5_System_RegisterDSP(coreSystem.handle, FMOD_ResonanceAudioListener_GetDSPDescription(), IntPtr.Zero);
            reportResult(result, "Registering static plugin 'FMOD_ResonanceAudioListener_GetDSPDescription'");
        }
    }
}

#endif // ENABLE_IL2CPP
